name: Scheduled Job

env:
  TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
  TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}

on:
  schedule:
    - cron: '*/4 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
