name: Scheduled Job

on:
  schedule:
    # 8-23 in Germany (UTC+2), means 22-13 in Pacific Time (UTC-8) where GitHub's servers are located
    - cron: '*/4 22-13 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
