name: Scheduled Job

env:
  TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
  TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}

# TODO: How to populate the scraped_flat_ids.txt?
# TODO: How to set the cron job if the servers of GitHub are in Pacific time (GMT-8), but I'm in GMT+2

#on:
#  schedule:
#    - cron: '*/4 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
